t=int(input())
for _ in range(t):
    k,a,b,x,y=map(int,input().split())
    ans=0
    if(x<y):
        if(k>=a):
            c1=k-a
            q1=c1//x
            ans+=q1
            k=k-(q1*x)
        if(k>=a):
            ans+=1
            k=k-x
        if(k>=b):
            c2=k-b
            q2=c2//y
            ans+=q2
            k=k-(q2*y)
        if(k>=b):
            ans+=1
            k=k-y
    elif(x>y):
        if(k>=b):
            c2=k-b
            q2=c2//y
            ans+=q2
            k=k-(q2*y)
        if(k>=b):
            ans+=1
            k=k-y
        if(k>=a):
            c1=k-a
            q1=c1//x
            ans+=q1
            k=k-(q1*x)
        if(k>=a):
            ans+=1
            k=k-x
    else:
        if(a>b):
            if(k>=a):
                c1=k-a
                q1=c1//x
                ans+=q1
                k=k-(q1*x)
            if(k>=a):
                ans+=1
                k=k-x
            if(k>=b):
                c2=k-b
                q2=c2//y
                ans+=q2
                k=k-(q2*y)
            if(k>=b):
                ans+=1
                k=k-y
        else:
            if(k>=b):
                c2=k-b
                q2=c2//y
                ans+=q2
                k=k-(q2*y)
            if(k>=b):
                ans+=1
                k=k-y
            if(k>=a):
                c1=k-a
                q1=c1//x
                ans+=q1
                k=k-(q1*x)
            if(k>=a):
                ans+=1
                k=k-x
    print(ans)
        